[package]
name = "souporcell"
version = "2.4.0"
authors = ["wheaton5 <whheaton@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "~2.27.0", features = ["yaml"]}
hashbrown = "0.1"
rand = "0.7.0"
itertools = "*"
statrs = "*"
rayon = "*"
vcf = "0.1.0"
flate2 = "*"
